###################  项目启动端口  ###################
server:
  port: 7777
  error:
    whitelabel:
      enabled: false
  compression:
    min-response-size: 512 #压缩文件最小大小(kb)
    enabled: true #是否压缩
    mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg #要压缩的文件格式
###################  spring配置  ###################
spring:
  freemarker:
    enabled: true
    template-loader-path: classpath:/view/, classpath:/templates/
    cache: false
  cache:
    type: redis
  messages:
    basename: i18n/messages   # 设置国际化配置文件存放在classpath:/i18n目录下
    encoding: utf-8           #设定message bundles编码方式，默认为UTF-8
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /view/
      suffix: .ftl
  http:
    encoding:
      force: true
  application:
    name: SB2
  resources:
    chain:
      cache: true
      compressed: true
    cache:
      period: 0s
  redis:
    # Redis数据库索引（默认为0）
    database: 2
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # 连接池配置
    # 连接超时时间（毫秒）
    timeout: 0s
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8
        # 连接池中的最小空闲连接
        max-active: 8
        max-wait: -1s
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sb2?useUnicode=true&characterEncoding=utf-8
    username: dev
    password: dev123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 配置
    druid:
      #初始化连接大小
      initialSize: 4
      #最小空闲连接数
      minIdle: 3
      #最大连接数
      maxActive: 5
      WebStatFilter:
        enabled: false
###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.bogon.sb2.**.entity
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      #capital-mode: true
      #序列接口实现类配置
      #key-generator: com.baomidou.springboot.xxx
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
      #驼峰下划线转换
      table-underline: true
    #自定义SQL注入器
    #刷新mapper 调试神器
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
logging:
  file: logs/sb2.log
  level:
    com.bogon.sb2: debug
    root: info